#!/bin/bash
# build.sh — Build & package mod into AML Compiler output format
# Usage: bash build.sh [GUID] [MOD_NAME]
# Example: bash build.sh net.wazitech.carwr CARWR

set -e

# Auto-detect GUID from main.cpp
if [ -z "$1" ]; then
  GUID=$(grep -oP 'MYMOD(?:CFG)?\(\K[^,]+' main.cpp 2>/dev/null | head -1)
  if [ -z "$GUID" ]; then
    GUID=$(grep -oP 'MYMODCFGNAME\(\K[^,]+' main.cpp 2>/dev/null | head -1)
  fi
else
  GUID="$1"
fi

# Auto-detect module name from Android.mk
if [ -z "$2" ]; then
  MOD_NAME=$(grep "LOCAL_MODULE :=" Android.mk | head -1 | awk '{print $3}')
else
  MOD_NAME="$2"
fi

if [ -z "$GUID" ]; then
  echo "ERROR: Could not detect GUID from main.cpp"
  echo "Usage: bash build.sh <GUID> <MOD_NAME>"
  exit 1
fi

ZIP_NAME="${MOD_NAME}.zip"
OUTPUT_DIR="output"

echo "=== Building ${MOD_NAME} (GUID: ${GUID}) ==="

# Clean previous
rm -rf "$OUTPUT_DIR" "$ZIP_NAME" libs/ obj/

# Build both ABIs
if command -v ndk-build &>/dev/null; then
    ndk-build -j$(nproc) APP_ABI=arm64-v8a,armeabi-v7a
elif [ -n "$ANDROID_NDK_HOME" ] && [ -f "$ANDROID_NDK_HOME/ndk-build" ]; then
    "$ANDROID_NDK_HOME/ndk-build" -j$(nproc) APP_ABI=arm64-v8a,armeabi-v7a
elif [ -n "$NDK_HOME" ] && [ -f "$NDK_HOME/ndk-build" ]; then
    "$NDK_HOME/ndk-build" -j$(nproc) APP_ABI=arm64-v8a,armeabi-v7a
else
    echo "ERROR: ndk-build not found."
    echo "Set ANDROID_NDK_HOME or add ndk-build to PATH."
    exit 1
fi

# Create output structure matching AML Compiler format
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR/configs"
mkdir -p "$OUTPUT_DIR/mods"
mkdir -p "$OUTPUT_DIR/files"

# Copy built .so files to mods/
for abi in arm64-v8a armeabi-v7a; do
    if [ -d "libs/$abi" ]; then
        cp libs/$abi/*.so "$OUTPUT_DIR/mods/" 2>/dev/null || true
    fi
done

# Create default config .ini file
cat > "$OUTPUT_DIR/configs/${GUID}.ini" << EOF
## ${MOD_NAME} Configuration
## Auto-generated by build.sh
EOF

# Create zip
cd "$OUTPUT_DIR"
zip -r "../$ZIP_NAME" .
cd ..

# Clean build artifacts
rm -rf "$OUTPUT_DIR" libs/ obj/

echo ""
echo "=== Done: ${ZIP_NAME} ==="
echo "Contents:"
unzip -l "$ZIP_NAME"
